Repository newbe36524/MVP-on-board, pull requests merged in 2022-07, with the labels that each got.

#10 Update README.md
  README.md
Labels: size/S

#11 添加提名流程
  nomination.md
Labels: size/S

#12 Update and rename nomination.md to MVP提名注意事项.md
  MVP提名注意事项.md
Labels: size/XS

#13 Update README.md
  README.md
Labels: size/L
